[package]
name = "soup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "soup"
path = "src/main.rs"

[lib]
name = "soup"
path = "src/lib.rs"

[dependencies]
arrayvec = "0.7"
rand = "0.8"
rand_chacha = "0.3.1"
blake3 = "1"
uuid = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
ctrlc = "3"
ratatui = "0.28"
crossterm = "0.28"

[profile.release]
opt-level = 3
lto = "thin"
